// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all assignments
	// (GET /assignments)
	ListAssignments(c *gin.Context, params ListAssignmentsParams)
	// Create a new assignment
	// (POST /assignments)
	CreateAssignment(c *gin.Context)
	// Get a single assignment
	// (GET /assignments/{id})
	GetAssignment(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListAssignments operation middleware
func (siw *ServerInterfaceWrapper) ListAssignments(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssignmentsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAssignments(c, params)
}

// CreateAssignment operation middleware
func (siw *ServerInterfaceWrapper) CreateAssignment(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAssignment(c)
}

// GetAssignment operation middleware
func (siw *ServerInterfaceWrapper) GetAssignment(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAssignment(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/assignments", wrapper.ListAssignments)
	router.POST(options.BaseURL+"/assignments", wrapper.CreateAssignment)
	router.GET(options.BaseURL+"/assignments/:id", wrapper.GetAssignment)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xWTW/bRhD9K4tpjwwpNznxphRtYMBNAwM9pTqsuSNpAu6HZ4cKBIH/vdilPkibjeFY",
	"Ny41H2/fvDfiARpvg3foJEJ9AMYYvIuYDx+1ucfHDqOkU+OdoMuPOoSWGi3kXfUtepfexWaLVqenwD4g",
	"Cw1FDIqmNj/KPiDUEIXJbaAvAJk9z/zSF6c3/uEbNgJ9emUwNkwhdYUabt1Ot2QUHxH2BXz28qfvnHkD",
	"2rcgusfoO25QOS9qnYGkoKFVrr6MkTbOHnFNO1sUbbRkTL8yrqGGX6rLcKpjmeoPJyT7v07RfQHsO8Fb",
	"M8twFM0Sl7nf2rPVAjUYLfhOyCIUsxnSDVy4zkL9FQI6k34sQDdCu5SVcLUoaGA1U2KHW2raeUgJLz52",
	"xGhS7Uvo5R4j1Gc4q2f8F/CEiWeMNoxa0Lzm8jTPYhfM6yr1M3A/4/cfzf+6U7zeCFazyie39oO7xw5Y",
	"frlVa88qM09uo7RLBhUm3KUjk0GlzyTEUv3tGlShe2gpbtEUak3YmpjzIlrthJqobBdFMVpNTkXRDy2W",
	"/7p0a5I2AbtPZS/cquWXW0gUcBxg3ZSLcpFY8QGdDgQ1vC8X5XsoIGjZZvqrEax03mBmO00ob47EJNxR",
	"lOUoLuWztijIEeqvB6DU7rFD3kMBTtuB9qzgYrRzftJZ/aqYLujfFotX7ToStPGlBTMS6UXGmlnv55Ze",
	"okT59Xiqw9brrNW8P0Xotp2GFBB8nKH492zaEYZBrBjlozf7V932R5ecmrGfekK4w/4Z1TdXa/608xMT",
	"XYR83GBQwBa1ySI7wJ0fmj633z/3d2kUssVT5ojziQDPS6RjmtleCdSHQVtz9zgTU42+EHLKh5dTzn/S",
	"U5UMc1daOfw+Rp2ixt6sDmT6/zXoJ5SJdObsmSx/cScZeDr6MVHXduBVZHH8tngb4Z9QlFaR3KbFKeEp",
	"DHl3Iq3jFmrYioRYV5UOVDYk+3fC2sXgWcrG22p3A/2q/y8AAP//TaQO0k4KAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
