// Code generated by avro/gen. DO NOT EDIT.
package ports

// AssignmentCreated is a generated struct.
type AssignmentCreated struct {
	AssignmentID string  `avro:"assignmentId"`
	VehicleID    string  `avro:"vehicleId"`
	RouteID      string  `avro:"routeId"`
	Timestamp    string  `avro:"timestamp"`
	DriverID     *string `avro:"driverId"`
}

// NotificationIssued is a generated struct.
type NotificationIssued struct {
	RecipientID string `avro:"recipientId"`
	Channel     string `avro:"channel"`
	Message     string `avro:"message"`
	EventType   string `avro:"eventType"`
	Timestamp   string `avro:"timestamp"`
}
